version: '3.7'
services:
  pg:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=projects
    ports:
      - "5432:5432"
